title: Portfolio
email: demeritiusgriffin@gmail.com

minima:
  social_links:
    twitter: DemeritiusGriff
    github: demeritiusg
    linkedin: demeritius-griffin
    
highlighter: rouge 
   
theme: minima

plugins:
 - jekyll-feed
