title: Portfolio
# email: demeritiusgriffin@gmail.com

 # social media links in footer
#  social_links:
#    twitter: DemeritiusGriff
#    linkedin: https://www.linkedin.com/in/demeritius-griffin-bb476a7/
#    github: https://demeritiusg.github.io/
    
highlighter: rouge 
   
theme: jekyll-theme-slate

plugins:
 - jekyll-feed
