theme: jekyll-theme-slate

# general info
title: My portfolio
author: Demeritius Griffin
email: demeritiusgriffin@gmail.com

 # social media links in footer
  social_links:
    twitter: @DemeritiusGriff
    linkedin: https://www.linkedin.com/in/demeritius-griffin-bb476a7/
    github: https://demeritiusg.github.io/
    

plugins:
 - jekyll-feed
