title: Portfolio
author: Demeritius Griffin
email: demeritiusgriffin@gmail.com
#description: > 
#  This is used as a portfolio

show_excerpts: false # set to true to show excerpts on the homepage

minima:
  social_links:
    twitter: DemeritiusGriff
    linkedin: demeritius-griffin
    
highlighter: rouge 
   
theme: minima

plugins:
 - jekyll-feed
