title: Portfolio
email: demeritiusgriffin@gmail.com

minima:
 # social media links in footer
  social_links:
    twitter: DemeritiusGriff
    linkedin: demeritius-griffin
    github: demeritiusg
    
highlighter: rouge 
   
theme: minima

plugins:
 - jekyll-feed
